spring:
  profiles: development
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
#  resources:
#    static-locations: classpath:/WEB-INF/static/




application:
    data-source:
        base:
            jdbc-url: jdbc:mysql://localhost/chxylib?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
            username: root
            password: 123456
            pool-name: hikari-pool
            database: sipa_customer
            maximum-pool-size: 5
            connection-timeout: 30000
            idle-timeout: 600000
            connection-test-query: "SELECT 1"
            body-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
            database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
            show-sql: false
            generate-ddl: true
            properties:
                hibernate.id.new_generator_mappings: true
                hibernate.cache.use_second_level_cache: false
                hibernate.cache.use_query_cache: false
                hibernate.generate_statistics: true

server:
    port: 8888